changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major

    - title: New Features
      labels:
        - enhancement
        - semver-minor

    - title: Fixes
      labels:
        - bug
        - semver-patch
        - fix

    - title: Other Changes
      labels:
        - "*"